ct_organ_classes:
  "1": 'aorta'
  "2": 'gall_bladder'
  "3": 'kidney_left'
  "4": 'kidney_right'
  "5": 'liver'
  "6": 'pancreas'
  "7": 'postcava'
  "8": 'spleen'
  "9": 'stomach'
  "10": 'adrenal_gland_left'
  "11": 'adrenal_gland_right'
  "12": 'bladder'
  "13": 'celiac_trunk'
  "14": 'colon'
  "15": 'duodenum'
  "16": 'esophagus'
  "17": 'femur_left'
  "18": 'femur_right'
  "19": 'hepatic_vessel'
  "20": 'intestine'
  "21": 'lung_left'
  "22": 'lung_right'
  "23": 'portal_vein_and_splenic_vein'
  "24": 'prostate'
  "25": 'rectum'

ct_organ_colors:
  "0": [0.0, 0.0, 0.0]          # 000000 - black
  "1": [1.0, 0.882, 0.0]        # FFE100 - yellow - aorta
  "2": [0.941, 0.627, 1.0]      # F0A0FF - light pink - gall_bladder
  "3": [0.0, 0.459, 0.863]      # 0075DC - blue - kidney_left
  "4": [0.6, 0.247, 0.0]        # 993F00 - brown - kidney_right
  "5": [0.298, 0.0, 0.361]      # 4C005C - dark purple - liver
  "6": [0.098, 0.098, 0.098]    # 191919 - dark gray - pancreas
  "7": [0.0, 0.361, 0.192]      # 005C31 - dark green - postcava
  "8": [0.173, 0.812, 0.282]    # 2BCE48 - bright green - spleen
  "9": [1.0, 0.8, 0.6]          # FFCC99 - light orange - stomach
  "10": [0.502, 0.502, 0.502]   # 808080 - gray - adrenal_gland_left
  "11": [0.584, 1.0, 0.710]     # 94FFB5 - light green - adrenal_gland_right
  "12": [0.561, 0.486, 0.0]     # 8F7C00 - olive - bladder
  "13": [0.616, 0.8, 0.0]       # 9DCC00 - yellow green - celiac_trunk
  "14": [0.761, 0.0, 0.533]     # C20088 - magenta - colon
  "15": [0.0, 0.2, 0.502]       # 003380 - dark blue - duodenum
  "16": [1.0, 0.643, 0.020]     # FFA405 - orange - esophagus
  "17": [1.0, 0.659, 0.733]     # FFA8BB - light pink - femur_left
  "18": [0.259, 0.4, 0.0]       # 426600 - dark green - femur_right
  "19": [1.0, 0.0, 0.063]       # FF0010 - red - hepatic_vessel
  "20": [0.369, 0.945, 0.949]   # 5EF1F2 - cyan - intestine
  "21": [0.0, 0.6, 0.561]       # 00998F - teal - lung_left
  "22": [0.878, 1.0, 0.4]       # E0FF66 - light yellow - lung_right
  "23": [0.459, 0.039, 1.0]     # 740AFF - purple - portal_vein_and_splenic_vein
  "24": [0.6, 0.0, 0.0]         # 990000 - dark red - prostate
  "25": [1.0, 1.0, 0.502]       # FFFF80 - light yellow - rectum

lap_organ_classes:
  "0": "background"
  "1": "abdominal_wall"
  "2": "colon"
  "3": "liver"
  "4": "pancreas"
  "5": "small_intestine"
  "6": "spleen"
  "7": "stomach"

lap_organ_colors:
  "0": [0.0, 0.0, 0.0]          # 000000 - black
  "1": [1.0, 0.314, 0.020]      # FF5005 - red orange - abdominal_wall
  "2": [0.761, 0.0, 0.533]      # C20088 - magenta - colon
  "3": [0.298, 0.0, 0.361]      # 4C005C - dark purple - liver
  "4": [0.098, 0.098, 0.098]    # 191919 - dark gray - pancreas
  "5": [0.369, 0.945, 0.949]    # 5EF1F2 - cyan - small_intestine
  "6": [0.173, 0.812, 0.282]    # 2BCE48 - bright green - spleen
  "7": [1.0, 0.8, 0.6]          # FFCC99 - light orange - stomach